// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP6-k75OgOA-z6Dg6JXfvPNMpisG_2_n0',
    appId: '1:763758955069:web:f21d847fcdb2f4edae7854',
    messagingSenderId: '763758955069',
    projectId: 'cinsage-bfe68',
    authDomain: 'cinsage-bfe68.firebaseapp.com',
    storageBucket: 'cinsage-bfe68.appspot.com',
    measurementId: 'G-947EDDYW7L',
    databaseURL: "https://cinsage-bfe68-default-rtdb.firebaseio.com/",

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9DoOvydxXQ1_4dTMaU_lItUcJjF00Wo',
    appId: '1:763758955069:android:623b1a1366264460ae7854',
    messagingSenderId: '763758955069',
    projectId: 'cinsage-bfe68',
    databaseURL: "https://cinsage-bfe68-default-rtdb.firebaseio.com/",
    storageBucket: 'cinsage-bfe68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_--gOuMeA_HkBDrXEax3qQXqu22Vwko',
    appId: '1:763758955069:ios:bed920876a32c79eae7854',
    messagingSenderId: '763758955069',
    projectId: 'cinsage-bfe68',
    storageBucket: 'cinsage-bfe68.appspot.com',
    iosBundleId: 'com.z.cinsage.cinsage',
    databaseURL: "https://cinsage-bfe68-default-rtdb.firebaseio.com/",

  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_--gOuMeA_HkBDrXEax3qQXqu22Vwko',
    appId: '1:763758955069:ios:bed920876a32c79eae7854',
    messagingSenderId: '763758955069',
    projectId: 'cinsage-bfe68',
    storageBucket: 'cinsage-bfe68.appspot.com',
    iosBundleId: 'com.z.cinsage.cinsage',
    databaseURL: "https://cinsage-bfe68-default-rtdb.firebaseio.com/",

  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP6-k75OgOA-z6Dg6JXfvPNMpisG_2_n0',
    appId: '1:763758955069:web:92896e0550682a5bae7854',
    messagingSenderId: '763758955069',
    projectId: 'cinsage-bfe68',
    authDomain: 'cinsage-bfe68.firebaseapp.com',
    storageBucket: 'cinsage-bfe68.appspot.com',
    measurementId: 'G-W6QH5FWEYV',
    databaseURL: "https://cinsage-bfe68-default-rtdb.firebaseio.com/",

  );
}
